# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    game.card:
        class:        AppBundle\Utils\Game\Card\Card
        arguments:
    game.deck:
        class:        AppBundle\Utils\Game\Deck\Deck
        arguments:
    game.display.text:
        class:        AppBundle\Utils\Game\Display\Type\TextDisplayer
        arguments: